# Generated by Django 4.1.7 on 2023-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_researchpaper_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='date',
            field=models.DateField(),
        ),
    ]
