# Generated by Django 3.2.5 on 2023-06-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_car_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphoto',
            old_name='file',
            new_name='photos',
        ),
    ]
