# Generated by Django 3.2.5 on 2023-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_file_carphoto_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
