# Generated by Django 3.2.5 on 2023-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_car_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
