# Generated by Django 3.2.5 on 2023-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_car_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photos',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
