# Generated by Django 3.2.5 on 2021-08-10 01:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title'),
        ),
    ]
