# Generated by Django 3.2.5 on 2021-08-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210810_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='blog_title',
        ),
    ]
