# Generated by Django 3.2.5 on 2021-09-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='photo_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='blog_images/'),
        ),
    ]
