# Generated by Django 3.2.5 on 2024-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.URLField(default='johnjohnphotos.com'),
            preserve_default=False,
        ),
    ]
