# Generated by Django 3.2.5 on 2024-06-25 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogpost_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='value',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0.'), django.core.validators.MaxValueValidator(5, message='Rating must be at most 5.')]),
            preserve_default=False,
        ),
    ]
