# Generated by Django 3.2.5 on 2021-08-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_photo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='blog_title',
        ),
    ]
