# Generated by Django 3.2.5 on 2021-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210911_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=models.DateTimeField(verbose_name='date published'), upload_to='blog_images/'),
        ),
    ]
