# Generated by Django 3.2.5 on 2024-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(default='No location given', max_length=200),
            preserve_default=False,
        ),
    ]
