# Generated by Django 4.1.7 on 2023-06-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='paper',
            field=models.FileField(upload_to='research/'),
        ),
    ]
