# Generated by Django 4.1.7 on 2023-06-17 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_researchpaper_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
