# Generated by Django 3.2.5 on 2023-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_researchpaper_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='date',
            field=models.DateField(),
        ),
    ]
