# Generated by Django 3.2.5 on 2023-06-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230626_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphoto',
            old_name='case',
            new_name='car',
        ),
    ]
