# Generated by Django 3.2.5 on 2023-06-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_car_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
    ]
