# Generated by Django 3.2.5 on 2023-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_car_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
