# Generated by Django 3.2.5 on 2024-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20230626_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='cars/'),
        ),
    ]
